### ISSUE TITLE
Error with previewTemplate option after updating dropzone 

### ISSUE THREAD

**Issue by p0o** [felixrieseberg/React-Dropzone-Component#45] opened 2015-11-26 23:25 UTC
I'm having this error after updating all of my stack to react 0.14 which in case of dropzone it's somehow related to options I'm not using at all.

```
Uncaught TypeError: Cannot read property 'trim' of undefined
```
error is related to this line (not my code) :
 ```
file.previewElement = Dropzone.createElement(this.options.previewTemplate.trim());
```

Here is my code and as you can see I don't have previewTemplate as an option:

```javascript
renderImageUpload() {
		let componentConfig = {
			allowedFiletypes: ['.jpg', '.png'],
			postUrl: '/image_upload'
		};
		var eventHandlers = {
			removedfile: this.onImageRemoved,
			success: this.onImageUploaded
		};
		let djsConfig = {
			paramName: "image"
		};
		return <DropzoneComponent config={componentConfig} 
                       eventHandlers={eventHandlers} 
                       djsConfig={djsConfig} />;
	},
```

I do appreciate any kind of help. Thanks.

**Comment by felixrieseberg** [comment] 2015-11-27 17:55
Weird, I'll take a look.

**Comment by felixrieseberg** [comment] 2015-11-28 16:39
Hey - using your code, I can't reproduce the issue. I used your code in https://github.com/felixrieseberg/React-Dropzone-Component/tree/issue45-test, maybe go and take a look - but with React 0.14.3, I can upload/delete using your code without any errors.

I'm closing this for now, but I'd love to figure out what's wrong and help you :hospital:. Do you have a reproduction repo for me somewhere?

**Closed by felixrieseberg** 2015-11-28 16:39 UTC

**Comment by p0o** [comment] 2015-11-29 17:37
Hi again, thanks for spending time on it , I understand there should be something wrong with my pipeline but it's a complex app and it's hard to isolate the component. However, I thought you might know better with more info. As you know the problem is with the addedfile method of dropzone original codebase, right here:

```javascript
addedfile: function(file) {
        var node, removeFileEvent, removeLink ....
        if (this.element === this.previewsContainer) {
          this.element.classList.add("dz-started");
        }
        if (this.previewsContainer) {
          file.previewElement = Dropzone.createElement(this.options.previewTemplate.trim()); // TypeError: Cannot read property 'trim' of undefined
          file.previewTemplate = file.previewElement;
```
I tried logging the "this" object there to see what's going on:

```
URL: function URL()
_callbacks: Object
clickableElements: Array[1]
element: div.filepicker.dropzone.dz-clickable.dz-started
files: Array[1]
hiddenFileInput: input.dz-hidden-input
listeners: Array[2]
options: Object
previewsContainer: div.filepicker.dropzone.dz-clickable.dz-started // Is it okay to have this property?
version: "4.2.0"
```

As you can see I have previewsContainer there which I didn't define and I also didn't find any trace of its addition by your component. Obviously when it's there and previewTemplate is not defined the error might happen. 

Any ideas?

**Comment by kennyr** [comment] 2017-01-30 21:39
I'm getting this exact error myself. Has this been resolved?

**Comment by ohabash** [comment] 2018-05-24 15:27
anyone know what causes this? I am doing `import Dropzone from 'dropzone';`

```
var myAwesomeDropzone = new Dropzone("[dz1]", { url: "/file/post"});
		  myAwesomeDropzone.options = {
		    maxFilesize: 5,
		    addRemoveLinks: true,
		    dictResponseError: 'Server not Configured',
		    acceptedFiles: ".png,.jpg,.gif,.bmp,.jpeg",
		    init:function(){
		      var self = this;
		      // config
		      self.options.addRemoveLinks = true;
		      self.options.dictRemoveFile = "Delete";
		      //New file added
		      self.on("addedfile", function (file) {
		        console.log('new file added ', file);
		      });
		      // Send file starts
		      self.on("sending", function (file) {
		        console.log('upload started', file);
		        $('.meter').show();
		      });
		      
		      // File upload Progress
		      self.on("totaluploadprogress", function (progress) {
		        console.log("progress ", progress);
		        $('.roller').width(progress + '%');
		      });

		      self.on("queuecomplete", function (progress) {
		        $('.meter').delay(999).slideUp(999);
		      });
		      
		      // On removing file
		      self.on("removedfile", function (file) {
		        console.log(file);
		      });
		    }
		  };
```

which results in `Cannot read property 'trim' of undefined`

**Comment by camilolucena88** [comment] 2022-07-24 14:17
How did you solve this?
