### ISSUE TITLE
Issues with example

### ISSUE THREAD

**Issue by approots** [felixrieseberg/React-Dropzone-Component#27] opened 2015-09-19 16:04 UTC
The example http://reactdropzone.azurewebsites.net/example/ doesn't display on Firefox 40 and will crash Chrome 45 if anything but small files are dropped.

**Comment by felixrieseberg** [comment] 2015-09-20 21:18
Hey, I can't reproduce your issues with the upload - the sample is served by a mini Node server that might break if you do anything serious, but it should work just fine. I just tested with a 10mb and 1gb, which was okay.

Thanks for telling me about the Firefox issue though! Somehow, some ES6 (unsupported by Firefox) made it into the example - that's now fixed. Thanks again!

**Closed by felixrieseberg** 2015-09-20 21:18 UTC

**Comment by approots** [comment] 2015-09-25 20:32
Turns out it's a problem with your component, but with dropzone.js and Windows 7 64 bit: https://github.com/enyo/dropzone/issues/568
