### ISSUE TITLE
How to show already uploaded files in dropezone

### ISSUE THREAD

**Issue by lgt** [felixrieseberg/React-Dropzone-Component#80] opened 2016-06-09 21:17 UTC
The component from default works and thanks  for this work. But I'm not able to figure out how to show already uploaded files.

I see the `eventHandlers` which supposed to handle `init` dropzone but my function does not get triggered

I try the following

```
class Uploader extends React.Component {
    render() {
      return(
          <div>
            <DropzoneComponent
                config={componentConfig}
                eventHandlers={eventHandlers}
                //djsConfig={djsConfig}
            />
          </div>
        )
    }
} 
```

than here is the handler 

```
var eventHandlers = {
    // This one receives the dropzone object as the first parameter
    // and can be used to additional work with the dropzone.js
    // object
    init: getUploads,
    // All of these receive the event as first parameter:
    drop: callbackArray,
    dragstart: null,
    dragend: null,
    dragenter: null,
    dragover: null,
    dragleave: null,
    // All of these receive the file as first parameter:
    addedfile: simpleCallBack,
    removedfile: null,
    thumbnail: null,
    error: null,
    processing: null,
    uploadprogress: null,
    sending: null,
    success: null,
    complete: null,
    canceled: null,
    maxfilesreached: null,
    maxfilesexceeded: null,
    // All of these receive a list of files as first parameter
    // and are only called if the uploadMultiple option
    // in djsConfig is true:
    processingmultiple: null,
    sendingmultiple: null,
    successmultiple: null,
    completemultiple: null,
    canceledmultiple: null,
    // Special Events
    totaluploadprogress: null,
    reset: null,
    queuecomplete: null
}
```

and the function 

```
var getUploads = [

    function () {
        console.log('get uploaded');
        alert()
    }
]
```

what I'm doing wrong?

**Comment by standayweb** [comment] 2016-06-10 16:54
The init function does not get triggered for me either.

**Comment by felixrieseberg** [comment] 2016-09-08 04:22
Hey! Sorry that I took forever to respond - I cannot reproduce the issue and will close this for now. If you're still working on it (and you still have the issue, please feel free to reopen - we'll work it out together then).

**Closed by felixrieseberg** 2016-09-08 04:22 UTC

**Comment by cinder92** [comment] 2018-07-26 18:12
@lgt  have you solved thid issue?

**Comment by davidfells** [comment] 2018-09-07 22:55
@felixrieseberg this issue still exists. When running the example even, init is never called. In my code, the addedFiles handler and config options work as expected but init does not. this.dropzone is always null, and the console.log never happens.

`
reactDropzoneConfig = {
    postUrl: '/someURL',
    iconFiletypes: ['.jpg', '.png', '.gif'],
    showFiletypeIcon: true
  }
  dropzoneConfig = {
    addRemoveLinks: true,
    acceptedFiles: "image/jpeg,image/png,image/gif",
    autoProcessQueue: false
  }
  dropzoneHandlers = { 
    init: dropzone => {
      console.log(dropzone);
      this.dropzone = dropzone;
    },
    addedfile: file => {
      this.setState({ files: [...this.state.files, file] });
    }
  }
<Dropzone 
              config={ this.reactDropzoneConfig }
              eHandlers={ this.dropzoneHandlers } 
              djsConfig={ this.dropzoneConfig } 
            />
`

**Comment by davidfells** [comment] 2018-09-07 23:03
Similar issue, init & removedFiles do not work for me. See https://hastebin.com/ugibudevof.js

addedFiles works fine
